sudo: false
language: scala
scala:
  - 2.11.7
  - 2.10.6
jdk:
  - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
  - sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database levar;' -U postgres
after_success:
  -sbt coveralls
